[project]
name = "mcp-sdk-server"
version = "0.0.1"
description = "Python SDK MCP Server"
authors = [{ name = "John Doe" }]
dependencies = [
    "uipath-mcp>=0.0.101, <0.1.0",
]
requires-python = ">=3.11"
