[project]
name = "mcp-longrunning-server"
version = "0.0.1"
description = "Long Running Operations MCP Server"
authors = [{ name = "John Doe" }]
dependencies = [
    "uipath-mcp>=0.0.78, <0.1.0",
]
requires-python = ">=3.10"
